### ISSUE TITLE
Parámetros para aprox por Taylor

### ISSUE THREAD

**Issue by ivancastro10** [analysic-nabla-bootcamp/intro-python#4]
Creo que en la tarea hubo un error en el último inciso del ejercicio de B-S.
El 0.01% si corresponde a la variación de rho?? según yo sería a la variación de r, ya que incluso faltaría ese dato para poder valuar la formula, según yo. 

Quedo al pendiente, gracias.

**Comment by gerdm** [comment]
Hola @ivancastro10,

Sí, tienes razón, la formula debería ser $\Delta r = 0.01%$

**Comment by gerdm** [comment]
Parámetro actualizado
