### ISSUE TITLE
Duda - Tarea 02

### ISSUE THREAD

**Issue by alejandrareyesv** [analysic-nabla-bootcamp/intro-python#6]
Hola Gera, 

En el ejercicio 3 de la Tarea 2 (de la función _cercano_ ), se menciona que se encuentre los números que más se aproximen en valor absoluto al número base. Viendo el ejemplo 2, no se están tomando los valores como si estuvieran en valor absoluto sino únicamente como los números que más se aproximan pero sí toman en cuenta los signos.

¿Sería sólo la aproximación?

**Comment by gerdm** [comment]
Hola Ale,

Del ejemplo 2, los valores ordenados serían

```
[-29, -28, -26, -25, -23, -22, -12, -12,   8,   8,   9,  20,  20, 27,  29]
```
El elemento más cercano a `-3` del _array_ en valor absoluto sí sería `-12`; el siguiente siendo `8`:

* `|-3 - (-12)| = 9`
* `|-3 - 8| = 11`

¿Es esta tu duda?

**Comment by alejandrareyesv** [comment]
De acuerdo, es que había entendido que sólo se tomaría el valor absoluto de -3 pero ya ví que es de la diferencia.

¡Muchas gracias!
