### ISSUE TITLE
Duda tarea03, ejercicio 2

### ISSUE THREAD

**Issue by mnaudep** [analysic-nabla-bootcamp/intro-python#7]
Hola!

Una duda, no entiendo que es lo que que tiene que venir en los valores del ejercicio 2 de la tarea 3. A que se refiere con "  La función deberá regresar un diccionario con llaves los valores 0 al n y valores **una lista con los valores únicos de unidades para cada número** "

Muchas gracias!

**Comment by gerdm** [comment]
Hola @mnaudep,

Por ejemplo, para la llave `2`, las potencias de `2` del `0` al `10` serían:

```
[1, 2, 4, 8, 16, 32, 64, 128, 256, 512
```

Las unidades estarían dadas por

```
[1, 2, 4, 8, 6, 2, 4, 8, 6, 2]
```

Que tendría como valores únicos:
```
 [1, 2, 4, 6, 8]
```

¿Queda un poco más claro con esto?

**Comment by t-antol** [comment]
A mi tampoco me queda claro ... podrías poner mas ejemplos de eso porfa

**Comment by gerdm** [comment]
Claro @t-antol,

La finalidad del ejercicio es obtener todas las unidades de un número elevado a las potencias `0` al `n`. Si consideramos `n=5`, tendríamos que las potencias del `0` al `5` serían:

Para `1`,
```
[1, 1, 1, 1, 1]
```

Para `2`,
```
[1, 2, 4, 8, 16, 32]
```

Para `3`,
```
[1, 3, 9, 27, 81, 243]
```

Y así sucesivamente...

De estos tres arreglos, tendríamos que las unidades para cada uno de los elementos serían:

* `[1]` Para `1`
* `[1, 2, 4, 6, 8]` Para `2`,
* `[1, 3, 7, 9]` Para `3`,

Es decir, nos estamos enfocando en el último dígito de de cada potencia elevado a ese número y el arreglo final es una lista con los valores únicos.

Para este ejemplo, nuestra función debería regresar:

```python
{
    1: [1],
    2: [1, 2, 4, 6, 8],
    3: [1, 3, 7, 9]
}
```
¿Queda un poco más claro?

**Comment by t-antol** [comment]
si. gracias
